[id="proc-subscribing-sso-installing-sso_{context}"]
==== Subscribing to the RH-SSO {project_versionDoc} repository and installing RH-SSO {project_versionDoc}

.Prerequisites

* Ensure that your Red Hat Enterprise Linux system is registered to your account using Red Hat Subscription Manager. For more information see the link:https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/quick_registration_for_rhel/index[Red Hat Subscription Management documentation].
* Ensure that you have already subscribed to the {appserver_name} {appserver_version} repository. For more information see xref:subscribing_EAP_repo[Subscribing to the {appserver_name} {appserver_version} repository].

.Procedure

To subscribe to the RH-SSO {project_versionDoc} repository and install RH-SSO {project_versionDoc}, complete the following steps:

. For Red Hat Enterprise Linux 6, 7: Using Red Hat Subscription Manager, subscribe to the RH-SSO {project_versionDoc} repository using the following command. Replace <RHEL_VERSION> with either 6 or 7 depending on your Red Hat Enterprise Linux version.
+
[source,bash,subs="attributes+"]
----
subscription-manager repos --enable=rh-sso-{project_versionDoc}-for-rhel-<RHEL-VERSION>-server-rpms
----

. For Red Hat Enterprise Linux 8: Using Red Hat Subscription Manager, subscribe to the RH-SSO {project_versionDoc} repository using the following command:
+
[source,bash,subs="attributes+"]
----
subscription-manager repos --enable=rh-sso-{project_versionDoc}-for-rhel-8-x86_64-rpms
----

. For Red Hat Enterprise Linux 6, 7: Install RH-SSO from your subscribed RH-SSO {project_versionDoc} repository using the following command:
+
[source,bash,subs="attributes+"]
----
 yum groupinstall rh-sso7
----

. For Red Hat Enterprise Linux 8: Install RH-SSO from your subscribed RH-SSO {project_versionDoc} repository using the following command:
+
[source,bash,subs="attributes+"]
----
 dnf groupinstall rh-sso7
----

Your installation is complete. The default RH-SSO_HOME path for the RPM installation is /opt/rh/rh-sso7/root/usr/share/keycloak.

.Additional resources

For details on installing the {project_version} patch for {project_name}, see link:https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/{project_version_base}/html/upgrading_guide/upgrading#rpm-patching[RPM patching].
